version: "3"

services:
  database-quiz:
    image: postgres:alpine
    restart: always
    network_mode: bridge
    expose:
      - 9032
    ports:
      - "9032:5432"
    volumes:
      - quizdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=quiz_service
  app-template:
    build:
      context: ./../quiz_service # necessary because otherwise docker-compose overrides the context path when merging multiple docker-compose.yml files
      dockerfile: Dockerfile
    restart: always
    container_name: quiz_service
    expose:
      - 9000
      - 9001
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - database-quiz
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database-quiz:9032/quiz_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
  dapr-template:
    image: "daprio/daprd"
    command: [
      "./daprd",
      "--app-id", "quiz_service",
      "--app-port", "9001",
      "--dapr-http-port", "9000",
      "--resources-path", "./components"
    ]
    volumes:
      - "./../quiz_service/components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
    depends_on:
      - app-template
      - redis
    network_mode: "service:app-quiz"
  redis:
    image: "redis:alpine"
    expose:
      - "6379"
volumes:
  quizdata:
  testdata:
networks:
  default:
    name: dapr-network
    external: true